### ISSUE TITLE
Importing gcore_k8sv2 is broken

### ISSUE THREAD

**Issue by zadjadr** [G-Core/terraform-provider-gcore#72]
When importing an existing cluster previously created with terraform, the output shows multiple reasons the cluster needs to be replaced. The cluster deployment is exactly the same as in the terraform files, so I would expect no changes/reasons for replacement:

```# gcore_k8sv2.drt must be replaced
-/+ resource "gcore_k8sv2" "drt" {
      ~ created_at         = "Thursday, 08-Feb-24 11:28:38 UTC" -> (known after apply)
      ~ creator_task_id    = "6bc1e2e8-7efb-4895-90db-4f78381bdcac" -> (known after apply)
      ~ id                 = "drt" -> (known after apply)
      + is_ipv6            = true
      ~ is_public          = true -> (known after apply)
        name               = "drt"
      + pods_ipv6_pool     = "2a03:90c0:88:393::/64" # forces replacement
      + services_ipv6_pool = "2a03:90c0:88:381::/108" # forces replacement
      ~ status             = "Provisioned" -> (known after apply)
      + task_id            = (known after apply)
        # (6 unchanged attributes hidden)

      ~ pool {
          ~ created_at           = "Thursday, 08-Feb-24 11:28:38 UTC" -> (known after apply)
          ~ name                 = "medium-elastic" -> "medium-static"
          ~ node_count           = 2 -> (known after apply)
          ~ status               = "Running" -> (known after apply)
            # (7 unchanged attributes hidden)
        }
      ~ pool {
          ~ created_at           = "Tuesday, 13-Feb-24 10:55:50 UTC" -> (known after apply)
            name                 = "medium-static-mem"
          ~ node_count           = 1 -> (known after apply)
          ~ status               = "Running" -> (known after apply)
            # (7 unchanged attributes hidden)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

## How to reproduce

- Create cluster with `terraform apply`
- Remove cluster from state via `terraform state rm ..`
- Import cluster via `terraform import ..`

**Comment by gbernady** [comment]
Hey, the problem you're seeing is caused by the fact that the resource definition does not match the Terraform state file after import.

Specifically, the `*_ip_pool` attributes are optional and write-only. The values put there are not returned by the API, causing the mismatch. There is a plan to return those values in the future, but even then you may see changes reported by `terraform apply` in case all optional attributes are not matching the state file exactly.

Did you try generating a plan for the import with `terraform plan -generate-config-out=generated_resources.tf` and then running `terraform import`? It should generate resource definitions that match what will end up in the state file and the error you are seeing should not occur.

**Comment by zadjadr** [comment]
Thanks for the reply! I tried to generate the config but the only thing it does it replace those values with `null`:

```hcl
  pods_ipv6_pool     = null
  services_ipv6_pool = null
  is_ipv6            = null

  pods_ip_pool       = null
  services_ip_pool   = null
```

But applying this might break the cluster..

**Comment by gbernady** [comment]
Hi. I am terribly sorry to reply so late.

We did finally manage fix this issue by making mentioned fields read-write instead of write-only on the backend, and doing some tweaks on the provider side.
